# Generated by Django 5.2.8 on 2025-11-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_failed_attempts_user_lockout_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lockout_until',
        ),
    ]
