# Generated by Django 5.2.8 on 2025-11-13 19:31

import tokens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_remove_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(default=tokens.models.default_client_id, max_length=100, unique=True)),
                ('client_secret', models.CharField(default=tokens.models.default_client_secret, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
