# Generated by Django 5.2.8 on 2025-11-13 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolechangelog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='rolechangelog',
            name='change_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rolechangelog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_change_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolechangelog',
            name='new_roles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rolechangelog',
            name='old_roles',
            field=models.TextField(blank=True),
        ),
    ]
