# Generated by Django 5.2.8 on 2025-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_passwordresetlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetlog',
            name='outcome',
            field=models.CharField(choices=[('request', 'Password Reset Requested'), ('verify', 'Password Reset OTP Verified'), ('reset', 'Password Reset Completed')], max_length=20),
        ),
    ]
