# Generated by Django 5.2.8 on 2025-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_passwordresetlog_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetlog',
            name='outcome',
            field=models.CharField(choices=[('request', 'Password Reset Requested'), ('verify', 'Password Reset OTP Verified'), ('complete', 'Password Reset Completed'), ('reset', 'Password Reset Completed')], max_length=20),
        ),
    ]
